name: Codacy Quality Scan

on:
  workflow_dispatch:
  schedule:
    - cron: '43 3 * * 1'

permissions:
  contents: read

jobs:
  codacy-quality-scan:
    permissions:
      contents: read
    name: Codacy Quality Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@d840f886c4bd4edc059706d09c6a1586111c540b
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          verbose: true
          max-allowed-issues: 2147483647
